### PR TITLE
#57: Fix combination of tenant and group security in case user has no groups

### LINKED ISSUE #54: Wrong link
The link to the deployment guide
https://github.com/exasol/virtual-schemas/blob/master/doc/user-guide/deploying_the_virtual_schema_adapter.md
in the user guide 
https://github.com/exasol/row-level-security/blob/master/doc/user_guide/user_guide.md#installing-the-rls-virtual-schema-package
leads to nirvana.

### LINKED ISSUE #57: Invalid pushdown when combining tenant and group security
First of all thank you very much for fulfiling our needs and adding features. We really appreciate that.

- In our use case we tried to combine tenant and group security. 
- Some rows are aligned with user 'RLS_USER1', some with 'RLS_GROUP1' and some with both. 
- RLS_USER1 is not member of any group; RLS_USER2 is a member of RLS_GROUP1. 

When querying the tables with RLS_USER2, which has no assigned lines on tenant level, but is member of RLS_GROUP1 everything works as expected.
But when querying tables with RLS_USER1, which is not member of any group but has assigned rows on tenant level we get an invalid pushdown error.
To avoid invalid pushdowns, we have to assign every user at least one dummy group. Is this the correct way to deal with this issue, or are we missing something?

*of course I changed user and group names to make it easier to understand my point ;)
In this case user RLS_BEHR091 can only query the tables when a dummy group is assigned.

Thanks and best regards,
Jörg

2020-08-26 16_16_21-Start

### PR DESCRIPTION
**Pull request by redcatbear**
Closes #57. Closes #54.

### CODE REVIEW

File: src/test/java/com/exasol/adapter/dialects/rls/RowLevelSecurityLocalIT.java [hunk 1]
```diff
@@ -10,6 +9,7 @@
 class RowLevelSecurityLocalIT extends AbstractRowLevelSecurityIT {
     @Override
     protected Map<String, String> getVirtualSchemaProperties() {
-        return Collections.emptyMap();
+        // return Collections.emptyMap();
```
Comment (morazow) [inline src/test/java/com/exasol/adapter/dialects/rls/RowLevelSecurityLocalIT.java]:
```suggestion
```

File: src/test/java/com/exasol/adapter/dialects/rls/AbstractRowLevelSecurityIT.java [hunk 2]
```diff
@@ -126,6 +128,35 @@ void testGroupRestictedTable() throws SQLException {
...
+        final VirtualSchema virtualSchema = installVirtualSchema("VS_GROUP_AND_TENANT", sourceSchema);
+        final User user_t = factory.createLoginUser("USER_GT_T").grant(virtualSchema, SELECT);
+        final User user_g = factory.createLoginUser("USER_GT_G").grant(virtualSchema, SELECT);
+        final User user_gt = factory.createLoginUser("USER_GT_GT").grant(virtualSchema, SELECT);
+        final String sql = "SELECT * FROM " + virtualSchema.getFullyQualifiedName() + ".SOURCE_TABLE ORDER BY CITY";
+        assertAll(() -> assertThat(queryForUser(sql, user_t), table().row("Horta").row("Stockholm").matches()),
+                () -> assertThat(queryForUser(sql, user_g),
+                        table().row("Helsinki").row("Horta").row("Lhasa").row("Moskow").row("Stockholm").matches()),
+                () -> assertThat(queryForUser(sql, user_gt), table().row("Lhasa").row("Rio").matches()));
+    }
```
Comment (morazow) [inline src/test/java/com/exasol/adapter/dialects/rls/AbstractRowLevelSecurityIT.java:162]: This test required me short brain gymnastics, even though I know what I was looking.

Couple of suggestions if possible:

- Change user/tenant to identifiable names, e.g, Mike.
- Create expected list of cities for each user, e.g, `expectedCitiesForMike = Arrays.asList(/* tenant */ "Horta", /* Group Cold */ "Lhase")`.

**Review by morazow — CHANGES_REQUESTED** [review]

**Review by morazow — APPROVED** [review]
