### PR TITLE
#48: Updated dependencies. Added scan. Fixed broken dependencies.

### LINKED ISSUE #48: Prepare group security release
Prepare the release of the group security feature.

### PR DESCRIPTION
**Pull request by redcatbear**
Closes #48.

### CODE REVIEW

File: tools/version.sh [hunk 1]
```diff
@@ -8,32 +8,41 @@ readonly file_find_regex='.*\.(md|yaml|sql|java)'
...
 usage () {
-    log "Usage: $script help"
+    log "Usage: $script"
+    log "       $script help | -h | --help | usage"
     log "       $script verify"
     log "       $script unify"
     log
     log "Run from the root directory \"$root_dir\""
     log
+    log "Running the script without parameter returns the current version from the master"
```
Comment (morazow) [inline tools/version.sh]:
```suggestion
    log "Running the script without parameter returns the current version from the main"
```

File: tools/version.sh [hunk 2]
```diff
@@ -8,32 +8,41 @@ readonly file_find_regex='.*\.(md|yaml|sql|java)'
...
+    log "POM file."
+    log
     log "This script can serve as a checkpoint using 'verify' as command. The exit value"
     log "is zero when all detected version numbers match the ones on the master POM file."
```
Comment (morazow) [inline tools/version.sh]:
```suggestion
    log "is zero when all detected version numbers match the ones on the main POM file."
```

**Review by morazow — CHANGES_REQUESTED** [review]

**Review by morazow — APPROVED** [review]
